"""The one Verifiable Intent delegation the proof is built on.

Everything here is generated by the pinned official VI reference
implementation. Nothing is hand-rolled, stubbed or replayed from a
recorded string: the chain the proof verifies is the chain this module
just signed.

On determinism
--------------
The *outcomes* are deterministic — same cases, same decisions, same
reason codes, every run. The *bytes* are not, and must not be: ES256
signatures carry a random nonce and SD-JWT disclosures carry a random
salt, both by design. Pinning them would mean patching the reference
implementation's cryptography, which is exactly what the proof is not
allowed to do. So an artefact digest differs between runs and each
evidence file records the digest of the run that produced it.

The private keys below are fixed test values. They are published in this
file precisely so that nobody mistakes them for production material.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass
from decimal import Decimal
from typing import Any, Final

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

# --- identities ------------------------------------------------------------

#: The VI issuer this proof trusts. Naming Mastercard here identifies the
#: credential format's issuer field in the reference implementation's own
#: examples. It asserts no relationship with Mastercard; see the README.
ISSUER_ID: Final[str] = "https://www.mastercard.com"

#: Audience values. The mandate is addressed to the agent; the payment
#: fulfilment is addressed to the network that will act on it.
AGENT_AUDIENCE: Final[str] = "https://agent.verifiable-intent.example"
NETWORK_AUDIENCE: Final[str] = "https://www.mastercard.com"
WALLET_ISSUER: Final[str] = "https://wallet.example.com"

#: The VI credential subject the proof organisation registers for its agent.
VI_SUBJECT: Final[str] = "user-proof-principal-001"

#: Test private scalars. NOT SECRET — fixed so the proof is reproducible.
_ISSUER_D: Final[int] = 0x1A2B3C4D5E6F708192A3B4C5D6E7F80112233445566778899AABBCCDDEEFF01
_USER_D: Final[int] = 0x2B3C4D5E6F708192A3B4C5D6E7F80112233445566778899AABBCCDDEEFF0102
_AGENT_D: Final[int] = 0x3C4D5E6F708192A3B4C5D6E7F80112233445566778899AABBCCDDEEFF010203
#: A second agent key, for proving a delegation bound elsewhere is refused.
_OTHER_AGENT_D: Final[int] = 0x5E6F708192A3B4C5D6E7F80112233445566778899AABBCCDDEEFF0102030405

# --- what the delegation permits -------------------------------------------

SUPPLIER_A: Final[dict[str, str]] = {
    "id": "supplier-a",
    "name": "Supplier A",
    "website": "https://supplier-a.example",
}
SUPPLIER_B: Final[dict[str, str]] = {
    "id": "supplier-b",
    "name": "Supplier B",
    "website": "https://supplier-b.example",
}

#: VI permits USD up to this ceiling, per transaction. Inntris organisation
#: policy is deliberately narrower; that difference is the whole proof.
VI_MAX_AMOUNT: Final[Decimal] = Decimal("20000.00")
VI_MAX_MINOR_UNITS: Final[int] = 2_000_000
VI_CURRENCY: Final[str] = "USD"

#: A placeholder item, present because the reference implementation's
#: autonomous L2 pairs a checkout mandate with the payment mandate. The
#: proof reads only the payment side.
_ACCEPTABLE_ITEMS: Final[list[dict[str, str]]] = [
    {"id": "PROOF-ITEM-1", "title": "Proof line item"}
]


@dataclass(frozen=True)
class KeyPair:
    private_key: ec.EllipticCurvePrivateKey
    kid: str

    @property
    def public_key(self) -> ec.EllipticCurvePublicKey:
        return self.private_key.public_key()

    @property
    def public_jwk(self) -> dict[str, Any]:
        from verifiable_intent.crypto.signing import public_key_to_jwk

        return public_key_to_jwk(self.private_key)

    @property
    def public_pem(self) -> str:
        return self.public_key.public_bytes(
            Encoding.PEM, PublicFormat.SubjectPublicKeyInfo
        ).decode("ascii")


def _key(scalar: int, kid: str) -> KeyPair:
    return KeyPair(ec.derive_private_key(scalar, ec.SECP256R1()), kid)


def issuer_keys() -> KeyPair:
    return _key(_ISSUER_D, "mastercard-issuer-key-1")


def user_keys() -> KeyPair:
    return _key(_USER_D, "user-device-key-1")


def agent_keys() -> KeyPair:
    return _key(_AGENT_D, "agent-key-1")


def other_agent_keys() -> KeyPair:
    return _key(_OTHER_AGENT_D, "agent-key-2")


# --- the delegation --------------------------------------------------------


@dataclass(frozen=True)
class Delegation:
    """One signed L1 + L2 pair and the handles an L3 needs to bind to it."""

    l1_serialized: str
    l2_serialized: str
    l2_base_jwt: str
    payment_disclosure: str
    supplier_a_disclosure: str
    supplier_b_disclosure: str
    issued_at: int
    expires_at: int
    agent_public_jwk: dict[str, Any]

    def disclosure_for(self, payee_id: str) -> str:
        if payee_id == SUPPLIER_A["id"]:
            return self.supplier_a_disclosure
        if payee_id == SUPPLIER_B["id"]:
            return self.supplier_b_disclosure
        raise KeyError(f"no disclosure for payee {payee_id!r}")

    def l2_payment_presentation(self, payee_id: str) -> str:
        """What the payment recipient is shown for a payment to ``payee_id``.

        The payment mandate plus exactly the payee being paid. This is the
        presentation an L3a fulfilment commits to in its ``sd_hash``, so it
        is per-payee by construction: a presentation carrying a different
        set of disclosures hashes differently and the chain refuses it.
        """
        from verifiable_intent.crypto.disclosure import build_selective_presentation

        return build_selective_presentation(
            self.l2_base_jwt, [self.payment_disclosure, self.disclosure_for(payee_id)]
        )


def build_delegation(
    *,
    now: int | None = None,
    lifetime_seconds: int = 86_400,
    delegate: KeyPair | None = None,
    max_minor_units: int | None = VI_MAX_MINOR_UNITS,
    extra_payment_constraints: list[Any] | None = None,
    subject: str = VI_SUBJECT,
) -> Delegation:
    """Sign one autonomous VI delegation with the reference implementation.

    The defaults are the proof fixture: both suppliers permitted, USD up
    to 20,000.00, delegated to the proof agent's key. The keyword
    arguments exist so acceptance cases can vary exactly one thing —
    a different delegate, an unsupported constraint, a shorter life —
    without a second, divergent fixture.
    """
    from verifiable_intent.crypto.disclosure import hash_bytes
    from verifiable_intent.crypto.sd_jwt import decode_sd_jwt
    from verifiable_intent.issuance.issuer import create_layer1
    from verifiable_intent.issuance.user import create_layer2_autonomous
    from verifiable_intent.models.constraints import (
        AllowedMerchantConstraint,
        AllowedPayeeConstraint,
        CheckoutLineItemsConstraint,
        PaymentAmountConstraint,
    )
    from verifiable_intent.models.issuer_credential import IssuerCredential
    from verifiable_intent.models.user_mandate import (
        CheckoutMandate,
        MandateMode,
        PaymentMandate,
        UserMandate,
    )

    issued_at = int(time.time()) if now is None else int(now)
    expires_at = issued_at + int(lifetime_seconds)
    issuer = issuer_keys()
    user = user_keys()
    agent = delegate or agent_keys()
    payees = [SUPPLIER_A, SUPPLIER_B]

    l1 = create_layer1(
        IssuerCredential(
            iss=ISSUER_ID,
            sub=subject,
            iat=issued_at,
            exp=expires_at,
            aud=WALLET_ISSUER,
            cnf_jwk=user.public_jwk,
            email="principal@proof.example",
            pan_last_four="1234",
            scheme="Mastercard",
        ),
        issuer.private_key,
    )

    payment_constraints: list[Any] = [AllowedPayeeConstraint(allowed=payees)]
    if max_minor_units is not None:
        payment_constraints.insert(
            0, PaymentAmountConstraint(currency=VI_CURRENCY, max=max_minor_units)
        )
    payment_constraints.extend(extra_payment_constraints or ())

    mandate = UserMandate(
        nonce=str(uuid.uuid4()),
        aud=AGENT_AUDIENCE,
        iat=issued_at,
        iss=WALLET_ISSUER,
        exp=expires_at,
        mode=MandateMode.AUTONOMOUS,
        sd_hash=hash_bytes(l1.serialize().encode("ascii")),
        prompt_summary="Pay approved suppliers in USD up to 20,000.00",
        checkout_mandate=CheckoutMandate(
            vct="mandate.checkout.open.1",
            cnf_jwk=agent.public_jwk,
            cnf_kid=agent.kid,
            constraints=[
                AllowedMerchantConstraint(allowed=payees),
                CheckoutLineItemsConstraint(
                    items=[
                        {
                            "id": "line-item-1",
                            "acceptable_items": _ACCEPTABLE_ITEMS,
                            "quantity": 1,
                        }
                    ]
                ),
            ],
        ),
        payment_mandate=PaymentMandate(
            vct="mandate.payment.open.1",
            cnf_jwk=agent.public_jwk,
            cnf_kid=agent.kid,
            payment_instrument={
                "type": "mastercard.srcDigitalCard",
                "id": "00000000-0000-4000-8000-000000000001",
                "description": "Proof instrument **** 1234",
            },
            constraints=payment_constraints,
        ),
        merchants=payees,
        acceptable_items=_ACCEPTABLE_ITEMS,
    )
    l2 = create_layer2_autonomous(mandate, user.private_key)
    l2_serialized = l2.serialize()
    l2_base_jwt = l2_serialized.split("~")[0]

    parsed = decode_sd_jwt(l2_serialized)
    payment_disclosure = _find_disclosure(
        parsed, lambda v: isinstance(v, dict) and v.get("vct") == "mandate.payment.open.1"
    )
    supplier_a = _find_disclosure(
        parsed, lambda v: isinstance(v, dict) and v.get("id") == SUPPLIER_A["id"]
    )
    supplier_b = _find_disclosure(
        parsed, lambda v: isinstance(v, dict) and v.get("id") == SUPPLIER_B["id"]
    )
    if not (payment_disclosure and supplier_a and supplier_b):
        raise RuntimeError("the signed L2 did not carry the expected disclosures")

    return Delegation(
        l1_serialized=l1.serialize(),
        l2_serialized=l2_serialized,
        l2_base_jwt=l2_base_jwt,
        payment_disclosure=payment_disclosure,
        supplier_a_disclosure=supplier_a,
        supplier_b_disclosure=supplier_b,
        issued_at=issued_at,
        expires_at=expires_at,
        agent_public_jwk=agent.public_jwk,
    )


def build_payment_fulfilment(
    delegation: Delegation,
    *,
    payee: dict[str, str],
    minor_units: int,
    currency: str = VI_CURRENCY,
    transaction_id: str,
    now: int | None = None,
    lifetime_seconds: int = 300,
    signer: KeyPair | None = None,
) -> str:
    """Sign the agent's L3a fulfilment for one concrete payment."""
    from verifiable_intent.issuance.agent import create_layer3_payment
    from verifiable_intent.models.agent_mandate import (
        FinalPaymentMandate,
        PaymentL3Mandate,
    )

    issued_at = int(time.time()) if now is None else int(now)
    agent = signer or agent_keys()
    l3 = create_layer3_payment(
        PaymentL3Mandate(
            nonce=str(uuid.uuid4()),
            aud=NETWORK_AUDIENCE,
            iat=issued_at,
            iss="https://agent.example.com",
            exp=issued_at + int(lifetime_seconds),
            final_payment=FinalPaymentMandate(
                transaction_id=transaction_id,
                payee=payee,
                payment_amount={"currency": currency, "amount": minor_units},
                payment_instrument={
                    "type": "mastercard.srcDigitalCard",
                    "id": "00000000-0000-4000-8000-000000000001",
                    "description": "Proof instrument **** 1234",
                },
            ),
            final_merchant=payee,
        ),
        agent.private_key,
        delegation.l2_base_jwt,
        delegation.payment_disclosure,
        delegation.disclosure_for(payee["id"]),
        kid=agent.kid,
    )
    return l3.serialize()


def presented_evidence(
    delegation: Delegation, l3_payment: str, *, payee_id: str
) -> dict[str, str]:
    """The untrusted evidence mapping a caller hands to the provider.

    ``l2`` is the full mandate — it is what the delegated scope is read
    from. ``l2_payment`` is the narrower presentation the L3a fulfilment
    bound itself to, and it is what the chain check verifies that binding
    against.
    """
    return {
        "l1": delegation.l1_serialized,
        "l2": delegation.l2_serialized,
        "l3_payment": l3_payment,
        "l2_payment": delegation.l2_payment_presentation(payee_id),
    }


def _find_disclosure(sd_jwt: Any, predicate: Any) -> str | None:
    for text, value in zip(sd_jwt.disclosures, sd_jwt.disclosure_values, strict=False):
        if predicate(value[-1] if value else None):
            return text
    return None
